# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: Configure default language
  become: true
  ansible.builtin.template:
    src: 'etc/default/locale.j2'
    dest: '/etc/default/locale'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - Generate locales (debian)

- name: Configure desired locales
  become: true
  ansible.builtin.template:
    src: 'etc/locale.gen.j2'
    dest: '/etc/locale.gen'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - Generate locales (debian)
